
//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DbExport.MVVM.Catel_4._0._0.Catel.Test.Catel.Test.EntityFramework5.DbContextTest.NET40
{

using System;
    using System.Collections.Generic;
    
public partial class DbContextCustomer
{

    public DbContextCustomer()
    {

        this.DbContextOrders = new HashSet<DbContextOrder>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public string Street { get; set; }

    public string Country { get; set; }



    public virtual ICollection<DbContextOrder> DbContextOrders { get; set; }

}

}
