

//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DbExport.MVVM.Catel_4._0._0.Catel.Test.Catel.Test.EntityFramework5.DbContextTest.NET40
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class TestDbContextContainer : DbContext
{
    public TestDbContextContainer()
        : base("name=TestDbContextContainer")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<DbContextCustomer> DbContextCustomers { get; set; }

    public DbSet<DbContextOrder> DbContextOrders { get; set; }

    public DbSet<DbContextProduct> DbContextProducts { get; set; }

}

}

